Larry local branch
NCATComp410/comp410_spring_2022 pull request #215
Opened 2022-04-15 17:43 UTC by larrykimutai

2022-04-15 21:26 UTC, DAndreBrown approved these changes

2022-04-15 23:24 UTC, claesmk commented on pii_data.py
>          if self.__eq__('0:0:0:0:0:0:0:0') | self.__eq__(':::::::'):
You've used a [bitwise](https://www.w3schools.com/python/gloss_python_bitwise_operators.asp) operator here - you don't want to do that.  Instead you should use or like this:
```
        if self.__eq__('0:0:0:0:0:0:0:0') or self.__eq__(':::::::'):
```

2022-04-15 23:24 UTC, claesmk commented on test_pii_data.py
> +        print("\n" + test_data.has_ipv6(True))
This print does not actually test the anonymize functionality.  You want to do something like this:
```
        print("\n" + test_data.has_ipv6(True))
        self.assertEqual('[iPv6 address]',
                         test_data.has_ipv6(True))
```

2022-04-15 23:25 UTC, claesmk requested changes
See embedded comments

2022-04-18 14:26 UTC, claesmk approved these changes
Looks good

2022-04-18 14:26 UTC, merged