Bugsmasher email
NCATComp410/comp410_spring_2022 pull request #91
Opened 2022-02-22 22:17 UTC by wjbush

Email modifications

2022-02-23 17:58 UTC, claesmk requested changes
I think your code looks OK however you have the wrong branch selected - the way the pull request is set now it's going to the main branch.  You want it to go to the bug_smashers branch.  If you edit your pull request you can change it to the correct branch.

2022-02-23 20:09 UTC, wjbush commented
I believe the issues are now fixed.

On Wed, Feb 23, 2022 at 12:58 PM claesmk ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I think your code looks OK however you have the wrong branch selected -
> the way the pull request is set now it's going to the main branch. You want
> it to go to the bug_smashers branch. If you edit your pull request you can
> change it to the correct branch.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NCATComp410/comp410_spring_2022/pull/91#pullrequestreview-891463884>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALEHLM5EC7MHQN5AYRZAUNDU4UN5JANCNFSM5PCVP6FA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-02-23 20:54 UTC, claesmk commented on test_pii_data.py
>          self.assertEqual(test_data.has_email(), None)
Does the unit test run OK?  This doesn't look right, I would expect your has_email() to return True not None

2022-02-23 20:54 UTC, claesmk reviewed
Please double-check and make sure your unit test runs OK

2022-02-24 02:59 UTC, claesmk approved these changes
Looks good thanks for fixing the unit tests

2022-02-24 14:08 UTC, claesmk commented
Reminder to @Terry0253 to review and approve this commit after that @wjbush you will be able to merge this pull request

2022-02-24 17:25 UTC, Terry0253 approved these changes
Looks good

2022-02-24 17:26 UTC, merged